name: Update Web Docs on Push

permissions: write-all

on:
  push:
    branches:
      - master

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Docs
      run: |
        sudo apt install -y nodejs
        mkdir vault
        cp -r `ls | grep -v vault` .vault/
        npm -g install @publishkit/cli
        kit init
        kit export test.md kitrc.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
